export default {
  LOGIN: 'LOGIN',
  USER_INFO: 'USER_INFO',
  NO_INTERNET: 'NO_INTERNET',
  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  CURRENT_BOOK_DATA: 'CURRENT_BOOK_DATA',
  AUDIO_BOOK: 'AUDIO_BOOK',
  HOME_DATA: 'HOME_DATA',
  USER_LANG: 'USER_LANG',
};
