export default {
  AppLogo: require('../../Assets/images/logo.png'),
  PlusIcon: require('../../Assets/images/plusicon.png'),
  ProfileImg: require('../../Assets/images/uprofile.png'),
  filterIcon: require('../../Assets/images/filter.png'),
  priceTag: require('../../Assets/images/price.png'),
  bankInfo: require('../../Assets/images/bill.png'),
  likes: require('../../Assets/images/likes.png'),
  links: require('../../Assets/images/link.png'),
  userprofile: require('../../Assets/images/profile.png'),
  feedback: require('../../Assets/images/feedback.png'),
  block: require('../../Assets/images/block.png'),
  upload: require('../../Assets/images/Upload.png'),
  Popper: require('../../Assets/images/popper.png'),
  stair: require('../../Assets/images/Stairs.png'),
  lang: require('../../Assets/images/lang.png'),
  line_height: require('../../Assets/images/line-height.png'),
  eventback: require('../../Assets/images/eventback.png'),
};
