export default {
  AppLogo: require('../../Assets/images/logo.png'),
  PlusIcon: require('../../Assets/images/plusicon.png'),
  ProfileImg: require('../../Assets/images/uprofile.png'),
  filterIcon: require('../../Assets/images/filter.png'),
  priceTag: require('../../Assets/images/price.png'),
  bankInfo: require('../../Assets/images/bill.png'),
  likes: require('../../Assets/images/likes.png'),
  links: require('../../Assets/images/link.png'),
  userprofile: require('../../Assets/images/profile.png'),
  feedback: require('../../Assets/images/feedback.png'),
  block: require('../../Assets/images/block.png'),
  upload: require('../../Assets/images/Upload.png'),
  Popper: require('../../Assets/images/popper.png'),
  stair: require('../../Assets/images/Stairs.png'),
  lang: require('../../Assets/images/lang.png'),
  line_height: require('../../Assets/images/line-height.png'),
  eventback: require('../../Assets/images/eventback.png'),
  newGroupBack: require('../../Assets/images/Rectangle_4231.png'),
  Security_Rules: require('../../Assets/images/Security_Rules.png'),
  Ticket: require('../../Assets/images/Ticket.png'),
  Pin_alt: require('../../Assets/images/Pin_alt.png'),
  ImageBackground: require('../../Assets/images/ImageBackground.png'),
  infoIcon: require('../../Assets/images/infoIcon.png'),
  followProfile: require('../../Assets/images/followProfile.png'),
  SearchNewGroup: require('../../Assets/images/SearchNewGroup.png'),
  backGroundGroup: require('../../Assets/images/5383010.png'),
  scanner: require('../../Assets/images/scanner.png'),
  blurpic: require('../../Assets/images/blurpic.png'),
  qrbackground: require('../../Assets/images/qrbackground.png'),
  Qrcode: require('../../Assets/images/Qrcode.png'),
  party: require('../../Assets/images/party.png'),
  fire:require('../../Assets/images/Fire.png'),
};
