export default {
  WelcomScreen: 'WelcomScreen',
  LoginScreen: 'LoginScreen',
  ReferalCode: 'ReferalCode',
  PhoneNumber: 'PhoneNumber',
  OtpVerification: 'OtpVerification',
  RegisterScreen: 'RegisterScreen',
  UploadImage: 'UploadImage',
  HomeScreen: 'HomeScreen',
  Search: 'Search',
  AddScreen: 'AddScreen',
  Chat: 'Chat',
  UserProfile: 'UserProfile',
  TabRoutes: 'TabRoutes',
};
